### ISSUE TITLE
Save new messages to file as they come in

### ISSUE THREAD

**Issue by ccdffddfddfdsfedeee** [xenova/chat-downloader#22] opened 2020-11-02 04:59 UTC
Is there a way to append new messages to the end of a file for a live video as they come in? Right now it only saves when you exit. Also, trying to send the output to a file using `>` results in an empty file.

**Comment by xenova** [comment] 2020-11-02 12:34
Sure, I could definitely add something to allow for this. Do you have anything particular in mind? Perhaps like a callback function you pass into the function - something which fires each time a new message is received?

**Comment by xenova** [comment] 2020-11-02 12:37
> Also, trying to send the output to a file using `>` results in an empty file.

What error occurs when this happens? Is it a UnicodeDecodeError? Or does nothing appear?

**Comment by ccdffddfddfdsfedeee** [comment] 2020-11-02 13:00
The file is created, but it is empty until exiting

**Comment by xenova** [comment] 2020-11-02 13:02
> The file is created, but it is empty until exiting

Are you perhaps doing a command like:
`python chat_replay_downloader "url" -output "output_file.txt" > output`, which will only complete once all messages are retrieved.

**Comment by ccdffddfddfdsfedeee** [comment] 2020-11-02 14:49
That command creates an empty file, then saves the chat to the file when exiting. It is not saving them as they come through.

This is the command: `python3 chat_replay_downloader.py https://www.youtube.com/watch?v=MtGUTs_HgcE > chat.txt`

**Comment by xenova** [comment] 2020-11-02 14:52
> That command creates an empty file, then saves the chat to the file when exiting. It is not saving them as they come through.
> 
> This is the command: `python3 chat_replay_downloader.py https://www.youtube.com/watch?v=MtGUTs_HgcE > chat.txt`

Okay I see 👍 I'll see what I can do and I'll get back to you as soon as possible.

**Comment by ccdffddfddfdsfedeee** [comment] 2020-11-03 14:48
Any updates?

**Comment by xenova** [comment] 2020-11-03 15:03
Hi! Yes, I finished implementing it yesterday, but had to finish a few university assignments before I could do proper testing.

I'm currently testing and I will update the master branch when everything is working.

**Comment by xenova** [comment] 2020-11-03 16:48
Okay - added.

It should be noted that only text files are capable of "appending" text. For csvs and json files, you sort of need to have all the data before writing to the file. However, this should suite your needs as you are writing to a text file anyway.

**Comment by ccdffddfddfdsfedeee** [comment] 2020-11-03 17:32
It is still not working and doing what it did before. Do you have to run it with a certain command?

**Comment by xenova** [comment] 2020-11-03 17:36
> It is still not working and doing what it did before. Do you have to run it with a certain command?

You should use the `-output` argument when writing to a file.
`python3 chat_replay_downloader.py https://www.youtube.com/watch?v=MtGUTs_HgcE -output chat.txt` instead of using output redirection (`>`).

**Comment by ccdffddfddfdsfedeee** [comment] 2020-11-03 18:45
That is working now, but there is a bug where no new messages appear, and it needs to be restarted to fix it.

**Comment by xenova** [comment] 2020-11-03 19:25
> That is working now, but there is a bug where no new messages appear when no one sends a message for a few minutes, and it needs to be restarted to fix it.

Can you give an example? Perhaps a video I can test with? I haven't encountered this issue before.

**Comment by ccdffddfddfdsfedeee** [comment] 2020-11-03 19:37
That video has the problem, you can use that one

**Comment by xenova** [comment] 2020-11-03 19:40
> That video has the problem, you can use that one

Okay I am testing now, however, it should be noted that very few messages are sent.

**Comment by xenova** [comment] 2020-11-03 20:22
Okay I see that there is indeed an issue. Let me see what I can do to fix it.

**Comment by xenova** [comment] 2020-11-04 01:50
This update should fix everything! 😃 There was something I didn't account for - when no messages are sent for a very long time. So, thanks for bringing this up! Always good to have lots of people testing!

I also made it so you can use standard output redirection (e.g. `> chat.txt`) as well. However, I would recommend using `-output chat.txt` as then you can output both to the console as well as to the file simultaneously.

Let me know if this works 👍

**Comment by ccdffddfddfdsfedeee** [comment] 2020-11-04 12:35
Testing right now

**Comment by ccdffddfddfdsfedeee** [comment] 2020-11-04 15:59
It worked! Is there a way to show the full link instead of the three dots when a link is posted? This is what it looks like right now:
![30FADD40-E26E-46C0-B17A-4A166D5C68BB](https://user-images.githubusercontent.com/61155247/98134206-80cb6480-1e8c-11eb-8339-0f316ffac4e5.jpeg)

**Comment by xenova** [comment] 2020-11-04 17:09
Great! 😃 I actually came across that yesterday when testing.
![image](https://user-images.githubusercontent.com/26504141/98142473-821e8080-1ed0-11eb-96f3-69d45c7ed5cd.png)

I think that happens because when displaying the text, it is also truncated. However, I do believe I can retrieve the original link. For your example, this is the data that is returned from YouTube:
```
"message":{
   "runs":[
      {
         "text":"The birds have gone to roost for the night. Please join us at the cam below for night critters. "
      },
      {
         "text":"https://www.youtube.com/watch?v=OIqUk...",
         "navigationEndpoint":{
            "clickTrackingParams":"CAEQl98BIhMI3ue4vL7n7AIVhKrVCh0IdA2j",
            "commandMetadata":{
               "webCommandMetadata":{
                  "url":"/watch?v=OIqUka8BOS8",
                  "webPageType":"WEB_PAGE_TYPE_WATCH",
                  "rootVe":3832
               }
            },
            "watchEndpoint":{
               "videoId":"OIqUka8BOS8"
            }
         }
      }
   ]
}
```

Then I would need to "recreate" the text by appending the value in navigationEndpoint->commandMetadata->webCommandMetadata. This might be different for different URLs however, so I would need to do more testing to see how normal URLs are parsed.

**Comment by ccdffddfddfdsfedeee** [comment] 2020-11-04 17:37
That is a good idea

**Comment by xenova** [comment] 2020-11-05 01:20
@ccdffddfddfdsfedeee Okay that should be good now. 👍

**Comment by ccdffddfddfdsfedeee** [comment] 2020-11-05 14:17
This also worked! One last question: Can you add a way to see if a message is from a moderator or the owner, like the blue and yellow icons on the site?

**Comment by xenova** [comment] 2020-11-05 14:38
That data is actually already retrieved, but is stored when writing to CSV and JSON only. However, this is only written at the end (or when exiting) because, to write to these types of files, you need to know all the data before hand (e.g. field names, which differ). I guess I can write it to the text file. Do you have any idea of what format you'd like?

It's currently like:
```
[2020-11-05 16:20:48] K M: Yes..the squirrels are very active at the cams..
[2020-11-05 16:21:02] Nightbot: Welcome all new viewers! However you found us, we're glad you're here. Please SUBSCRIBE and click the bell to be notified of new videos and cameras!
[2020-11-05 16:21:17] Nightbot: Watch a "behind the scenes" tour of the feeding area! https://www.youtube.com/watch?v=HNiNmAg3mcA
[2020-11-05 16:21:29] Svetlana Rodriguez: Thank you.
[2020-11-05 16:21:39] K M: Hello Svetlana
```
The same data is represented in JSON as:
```
   {
      "author":"K M",
      "author_id":"UCg_JA_HnmXl92vQmBy46ttA",
      "badges":"Moderator",
      "message":"Yes..the squirrels are very active at the cams..",
      "time_in_seconds":null,
      "timestamp":1604586048375916
   },
   {
      "author":"Nightbot",
      "author_id":"UCSvjQBDgYDB5TGVmCZObcwA",
      "badges":"Verified, Moderator",
      "message":"Welcome all new viewers! However you found us, we're glad you're here. Please SUBSCRIBE and click the bell to be notified of new videos and cameras!",
      "time_in_seconds":null,
      "timestamp":1604586062954293
   },
   {
      "author":"Nightbot",
      "author_id":"UCSvjQBDgYDB5TGVmCZObcwA",
      "badges":"Verified, Moderator",
      "message":"Watch a \"behind the scenes\" tour of the feeding area! https://www.youtube.com/watch?v=HNiNmAg3mcA",
      "time_in_seconds":null,
      "timestamp":1604586077970848
   },
   {
      "author":"Svetlana Rodriguez",
      "author_id":"UCub8TNfieRNtua0WiiwP-fQ",
      "message":"Thank you.",
      "time_in_seconds":null,
      "timestamp":1604586089449066
   },
   {
      "author":"K M",
      "author_id":"UCg_JA_HnmXl92vQmBy46ttA",
      "badges":"Moderator",
      "message":"Hello Svetlana",
      "time_in_seconds":null,
      "timestamp":1604586099386211
   }
```

But I imagine you want something like to be printed:
```
[2020-11-05 16:20:48] (Moderator) K M: Yes..the squirrels are very active at the cams..
[2020-11-05 16:21:02] (Verified, Moderator) Nightbot: Welcome all new viewers! However you found us, we're glad you're here. Please SUBSCRIBE and click the bell to be notified of new videos and cameras!
[2020-11-05 16:21:17] (Verified, Moderator) Nightbot: Watch a "behind the scenes" tour of the feeding area! https://www.youtube.com/watch?v=HNiNmAg3mcA
[2020-11-05 16:21:29] Svetlana Rodriguez: Thank you.
[2020-11-05 16:21:39] (Moderator) K M: Hello Svetlana
```

... I think this would be okay. But also, if you would like more advanced/custom features, you can always use the python module to do so 👍.

**Comment by ccdffddfddfdsfedeee** [comment] 2020-11-05 15:18
That is fine

**Comment by xenova** [comment] 2020-11-05 17:05
There we go 😃 Let me know if you have any other suggestions/ideas/requests. Otherwise, you can close the issue. 👍

**Comment by ccdffddfddfdsfedeee** [comment] 2020-11-05 22:42
What about showing AM/PM instead of 24 hour time?

**Comment by xenova** [comment] 2020-11-06 00:06
> What about showing AM/PM instead of 24 hour time?

Although that's how YouTube shows it, I think showing 24 hour time is better since it's more universal and aligns better to how normal times are displayed for replays. In general I would say 24 hour time is better.

If you want these features, you can always customise it by either changing the code (it is open source) or by importing the python module.

**Comment by ccdffddfddfdsfedeee** [comment] 2020-11-06 00:11
You could add it as an option when running the command

**Comment by xenova** [comment] 2020-11-06 14:31
> You could add it as an option when running the command

Okay I'm adding a system to customize print messages 👍

**Comment by ccdffddfddfdsfedeee** [comment] 2020-11-06 15:04
Also, why does it stop and say exit 1 after running for a long time? It only happens on one video and it needs to be restarted when this happens.

**Comment by xenova** [comment] 2020-11-06 15:08
Can you give an example? I've never had that issue. There's no point in the code where I explicitly call `exit(1)`, so I'm not too sure what problem that could be. No one has reported that yet either.

**Comment by ccdffddfddfdsfedeee** [comment] 2020-11-06 15:19
I am using two videos:
`https://www.youtube.com/watch?v=MtGUTs_HgcE` and
`https://www.youtube.com/watch?v=OIqUka8BOS8`

This is the command used for both of them: `python3 chat_replay_downloader.py https://www.youtube.com/watch?v=MtGUTs_HgcE --hide_output -output chat.txt &`

It only happens on the first video

**Comment by xenova** [comment] 2020-11-06 15:32
Okay that should easy to answer. The `&` is used to run the process in the background. This usually returns a code to say which process is being run. Is there a reason you want to do this? 

Also, if you want to, can you send a screenshot of the terminal? Just to make sure my hunch is correct.

**Comment by ccdffddfddfdsfedeee** [comment] 2020-11-06 15:44
The chat runs in the background and it saves to the file, but sometimes it stops saving to the file and says exit 1.

**Comment by xenova** [comment] 2020-11-06 15:49
Okay, but that information doesn't really help locate the problem (if there is one). I will run the command on my end and see if I experience any issues. Perhaps check that you don't lost internet connection? Or perhaps run the command with output shown so you can see what the problem is and send it here once it happens again.
`python3 chat_replay_downloader.py https://www.youtube.com/watch?v=MtGUTs_HgcE -output chat.txt &`

**Comment by ccdffddfddfdsfedeee** [comment] 2020-11-06 16:08
But it only happens on one video and I am running two on the same computer.

**Comment by xenova** [comment] 2020-11-06 16:16
> Or perhaps run the command with output shown so you can see what the problem is and send it here once it happens again.

Okay, but none of the information you have provided me will help find what the issue is. I am currently running the two links you mentioned above and I will see if any issues arise.

If you can, please provide console output for me to help debug.

**Comment by ccdffddfddfdsfedeee** [comment] 2020-11-06 16:27
I will, but it might take a few hours for it to happen

**Comment by ccdffddfddfdsfedeee** [comment] 2020-11-06 18:59
Any updates on the AM/PM time option?

**Comment by xenova** [comment] 2020-11-07 03:38
> I am currently running the two links you mentioned above and I will see if any issues arise.

After running it for 12 hours, no problems have occurred. This must have been an issue on your side. However, if you can provide evidence of the code being incorrect, I will look into it further.


> Any updates on the AM/PM time option?

Yes, this is coming soon.

**Comment by ccdffddfddfdsfedeee** [comment] 2020-11-07 03:41
The bug did not happen for me yet

**Comment by ccdffddfddfdsfedeee** [comment] 2020-11-10 20:02
It looks like the issue was fixed. Is there any more updates?

**Comment by xenova** [comment] 2020-11-10 20:08
> It looks like the issue was fixed. Is there any more updates?

Okay great. Yes, I am adding the AM/PM option soon, I just have some IRL things I have to finish first. I will finish it this weekend.

**Comment by ccdffddfddfdsfedeee** [comment] 2020-11-11 03:29
The issue happened again, it was because the connection was lost. Is there a way to auto restart it after this happens?

**Comment by xenova** [comment] 2020-11-13 03:18
Sure, I can add something to that effect. The AM/PM option is coming along too...

**Comment by ccdffddfddfdsfedeee** [comment] 2020-11-21 15:40
Any more updates?

**Comment by xenova** [comment] 2020-11-21 16:49
> Any more updates?

Hi there. I'm currently busy with some university work (which is due soon), so that has been my main priority. I will be finalising this all after the project is completed.

However, if you wish to have this completed sooner, I once again recommend you to take a look at using the python module. That was the original purpose of this tool: give people an "easy-to-use" python module to allow them to implement custom features.

The reason the AM/PM option is taking this long is because it requires a reworking of how messages are printed out, giving users the option to specify a format.

**Comment by Shingim** [comment] 2020-11-24 22:58
Hi, can you add an _optional arguments_ to disable ["Printing out badges of users in messages"](https://github.com/xenova/chat-replay-downloader/commit/4968db1dfd873ae4e4fa9682b8f6938b069bf64a)? I understand why it might be useful to some people but tbh, I don't really care about that and personally I would be better off without them written, like how it was before the update.

**Comment by xenova** [comment] 2020-11-25 00:33
> Hi, can you add an _optional arguments_ to disable ["Printing out badges of users in messages"](https://github.com/xenova/chat-replay-downloader/commit/4968db1dfd873ae4e4fa9682b8f6938b069bf64a)? I understand why it might be useful to some people but tbh, I don't really care about that and personally I would be better off without them written, like how it was before the update.

Hi 😃 Yes - I am working on a system to allow for users to specify any format they want to be printed. As I mentioned above, I have some university projects due soon, so I will only be able to add it afterwards (in around 5 days). But as always, if you want to do something custom in the meantime, you can use the python module.

**Comment by ccdffddfddfdsfedeee** [comment] 2020-11-30 23:52
It has been more than 5 days

**Comment by xenova** [comment] 2020-12-01 19:47
Working on it now :) This requires a lot of project restructuring... But I am working on it.

**Comment by Yay295** [comment] 2020-12-02 13:57
This issue seems to have expanded far beyond the initial problem. That said:

> That data is actually already retrieved, but is stored when writing to CSV and JSON only. However, this is only written at the end (or when exiting) because, to write to these types of files, you need to know all the data before hand (e.g. field names, which differ).

Why? I could see there being a difference between YouTube and Twitch, but once you've figured out which one of those you're reading from you should be able to use a standard template for all of the messages. You might end up with empty CSV columns this way, but in my opinion this is better than just not seeing anything at all until the end.

**Comment by xenova** [comment] 2020-12-02 14:52
> Why? I could see there being a difference between YouTube and Twitch, but once you've figured out which one of those you're reading from you should be able to use a standard template for all of the messages. You might end up with empty CSV columns this way, but in my opinion this is better than just not seeing anything at all until the end.

For example, when reading YouTube superchats, you don't know which types of messages you will be getting (e.g. sticker duration, sticker colour, etc.). So, unless there is some way to know what types of messages you will get, in advance, then I'm not too sure what the solution would be. Of course, we could just put all columns in, but that would result in a lot of empty columns.

I'm currently busy organising the code for package use (#24), as well as adding a custom format for printing (which has been spoken about a lot), so I'm quite busy with that at the moment. If you know of a way to add this, I'd be more than happy to add it. You can submit a PR if you want.

**Comment by ccdffddfddfdsfedeee** [comment] 2020-12-07 21:26
Done yet?

**Comment by xenova** [comment] 2020-12-07 21:37
> Done yet?

Your request requires a lot of reworking of the code. I have been working on this for the past week. (https://github.com/xenova/chat-replay-downloader/tree/package) 

Like I have said, for the past few weeks, if you want this to be implemented, you are more than welcome to code it in python using the provided module.

**Comment by ladalevis** [comment] 2020-12-12 07:22
> Done yet?

I made a pull request that could save all the available data into a db file, by default is chat_data.db in same folder. No matter any error happens, the data is always safe.

**Comment by xenova** [comment] 2021-06-30 21:48
The remaining functionality has been added to the latest version of the software.

---

Messages are saved as they come in (for all formats, including csv, json and text)

---

> What about showing AM/PM instead of 24 hour time?

The simplest way to do this would be to use the python module like [this](https://github.com/xenova/chat-downloader/issues/45#issuecomment-871742623)

Alternatively, you could define a custom formatting json file (e.g., `example.json`)
```json
{
    "12h": {
        "template": "{time_text|timestamp}{money.text}{author.display_name|author.name}{message}",
        "keys": {
            "time_text": "{} | ",
            "timestamp": {
                "template": "{} | ",
                "format": "%I:%M %p"
            },
            "money.text": "*{}* ",
            "message": ": {}"
        }
    }
}
```

then you can run the program using the `--format` and `--format_file` arguments:
```
chat_downloader https://www.youtube.com/watch?v=5qap5aO4i9A --format 24h --format_file example.json
```

which will produce output similar to:
```
11:40 PM | Wesley: you just lost the game 🙂
11:40 PM | Allan Ferreira: @Mia Alan Io ho 19 anni, e te?
11:40 PM | Giorgio Verzeletti: Vamo raga forza giuve siuuuuuummmm
11:41 PM | Fiore Diaz: @Leonor Meneses muy bien pa
11:41 PM | traw: Stinky monkey water
11:41 PM | Salman Amal: Who is doing their A levels?
11:41 PM | Aman Munjal: okh see ya later
11:41 PM | Leonardo: @Isabela Ramires Abri mão das minhas férias kkkk
11:41 PM | Dictionary: hi vhs
```

---




> The issue happened again, it was because the connection was lost. Is there a way to auto restart it after this happens?

Restart functionality has been added and the decoding error has also been fixed 👍 

---

> Hi, can you add an _optional arguments_ to disable ["Printing out badges of users in messages"]

As described above, you can now specify custom formats.

**Closed by xenova** 2021-06-30 21:48 UTC
