### ISSUE TITLE
[BUG] chat_downloader.errors.UserNotFound: Unable to find user (bogus error)

### ISSUE THREAD

**Issue by krichbanana** [xenova/chat-downloader#127] opened 2021-10-01 00:17 UTC
## Basic information
- Program version: 0.1.9 at the time (since updated to 0.1.10)
- Python version: 3.9.7
- Operating system: Arch Linux x64, linux package 5.14.6-arch1-1 

## Describe the bug
The channel exists, but chat_downloader throws a "User not found" error. when it attempts to get a list of videos from channel, on rare occasion. The issue is transient and doesn't occur for any length of time.

### Otherwise, if using the python module, provide the following:

1. A [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example):
```python
    downloader = ChatDownloader() 
    youtube = downloader.create_session(YouTubeChatDownloader)
    for video_status in ['upcoming', 'live', 'all']:
        for basic_video_details in youtube.get_user_videos(channel_id=channel_id, video_status=video_status): 
            pass  # processing here...
```
2. Output, traceback or other information relating to the bug:
```
Traceback (most recent call last):
  ...client code...
    for basic_video_details in youtube.get_user_videos(channel_id=channel_id, video_status=video_status):
  File "$HOME/.local/lib/python3.9/site-packages/chat_downloader/sites/youtube.py", line 1183, in get_user_videos
    raise UserNotFound(f'Unable to find user: "{user_url}"')
chat_downloader.errors.UserNotFound: Unable to find user: "https://www.youtube.com/channel/UCxxxxxxxxxxxxxxxxxxxxxx"

```

## Expected behavior
chat_downloader, when calling get_user_videos for a real, unsuspended channel, should get a list of all the videos on that channel tab. 

## Additional context/information
I suspect this may be a case of YouTube not returning data, perhaps a HTTP 500-type error or similar. I do not think it is a HTTP 429 error, since that is a more long-lasting condition, and causes chat_downloader to throw a parse error instead.

**Comment by SuperSonicHub1** [comment] 2021-10-30 03:01
Could you tell us what the channel is?

**Comment by xenova** [comment] 2022-11-30 22:32
Closing since I am unable to reproduce it. 

A similar issue also was raised in #174 (due to some HTML-related changes), so, it might have been something similar?

**Closed by xenova** 2022-11-30 22:32 UTC
Labels: bug
